includes:
- configs/water/base_no_amsgrad.yml

model:
  name: dimenetplusplus_sh
  hidden_channels: 128
  out_emb_channels: 256
  int_emb_size: 64
  basis_emb_size: 8
  num_blocks: 4
  cutoff: 3.0
  envelope_exponent: 5
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: True
  otf_graph: True

  mesh_cutoff: 5.0
  mesh_conv_layers: 3
  mesh_partition: 20
  mesh_conv_modes: 10

  mesh_channel: 12
  mesh_hidden_channel: 24

  using_ff: False


optim:
  loss_force: l2mae
