includes:
- configs/water/base_no_amsgrad.yml

model:
  name: dimenetplusplus_pme_v2
  hidden_channels: 128
  out_emb_channels: 256
  int_emb_size: 64
  basis_emb_size: 8
  num_blocks: 4
  cutoff: 5.0
  envelope_exponent: 5
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: True
  otf_graph: True


  num_filters: 64
  num_gaussians: 25

  mesh_cutoff: 10.0
  mesh_conv_layers: 2
  mesh_partition: 12
  mesh_conv_modes: 6
  mesh_channel: 16

  using_ff: False


optim:
  loss_force: l2mae
